### ISSUE TITLE
Downsampled output on LLIE-Platform 

### ISSUE THREAD

**Issue by Geniussh** [Li-Chongyi/Lighting-the-Darkness-in-the-Deep-Learning-Era-Open#15]
Hi, thank you for the great work of the LLIE-Platform! It is extremely helpful. 

However, I found the resolution of the output image has been downsampled for all methods. Is it possible to output the original resolution as the input?

**Comment by Li-Chongyi** [comment]
Hi,

Because of the limited GPU memory, we cannot produce the results of the
original resolutions when some methods used large networks.
Thus, the results cannot be used for quantitative analysis, just for visual
purposes. Thanks.



Kelvin Shen ***@***.***> 于2022年6月24日周五 14:25写道：
