### ISSUE TITLE
LOE metrics

### ISSUE THREAD

**Issue by Arusa1** [Li-Chongyi/Lighting-the-Darkness-in-the-Deep-Learning-Era-Open#18]
Hi! Thanks for the great survey!

I found the LOE (Lightness Order Error) metric is not available now. It  seems that I do not have the corresponding permission. Could you please provide it? Or is there any other way I can get it?

**Comment by Li-Chongyi** [comment]
Hi,

Please find the code here:
https://drive.google.com/drive/folders/0B3YzCh6G4aubLUhQMzdzR05nSDg?resourcekey=0-uHYoUQH9J-k1Y8ZzceVbOw

Best,


Arusa1 ***@***.***> 于2022年7月23日周六 14:09写道：

**Comment by Arusa1** [comment]
Great thanks! It helps me a lot.

**Comment by zzukong** [comment]
Hello, isn't LOE non-reference? Why do you need a reference image?

**Comment by Arusa1** [comment]
> Hello, isn't LOE non-reference? Why do you need a reference image?

Yes, you are right. LOE is a non-reference metric. I open this issue because the code for LOE provided by the author was not accessible at that time. So I ask for the new available link, which has nothing to do with the reference image (LOE is non-reference).
